# Server configuration
server:
  port: 8081 # Port number the server will run on

# Spring configuration
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/foodappdb # Database URL
  username: root # Database username
  password: Oracleroot@2510 # Database password
  driver-class-name: com.mysql.cj.jdbc.Driver # JDBC driver class name
 jpa:
  hibernate:
   ddl-auto: update # Hibernate auto DDL update strategy
   show-sql: true # Show SQL queries in logs
   database-platform: org.hibernate.dialect.MySQLDialect # Hibernate database dialect
 rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
    
#admin credentials    
admin:
  email: anniejaisinghani25@gmail.com
  password: annie@25    
  
mail:
  email: akanshajaisinghani@gmail.com
  password: kmmf wqbx ipsf minc
    
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
jwt:
  secret-key: azchsjkfiisjfsijjshdjakasldkdkafvgalkdnallllllllllldbbsnxjsmnfakbfk